// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.Infrastructure.Database;

#nullable disable

namespace University.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20230722094249_addAdminSeed")]
    partial class addAdminSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University.Domain.Entities.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaximalResult")
                        .HasColumnType("int");

                    b.Property<double>("MinimalResult")
                        .HasColumnType("float");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Exam", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.Faculties.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Faculty", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.LecturerSubjects.LecturerSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("LecturerSubject", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.Lecturers.Lecturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("QualificationYare")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lecturer", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.StudentSubjectExams.StudentSubjectExam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaximalResult")
                        .HasColumnType("int");

                    b.Property<double>("MinimalResult")
                        .HasColumnType("float");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.Property<Guid>("StudentSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId")
                        .IsUnique();

                    b.HasIndex("StudentSubjectId");

                    b.ToTable("StudentSubjectExam", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.StudentSubjects.StudentSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FacultyId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("GraduatedSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("FacultyId1");

                    b.ToTable("Student", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.SubjectPrograms.SubjectProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BookPages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectProgram", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Subject", "core");
                });

            modelBuilder.Entity("University.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirtsDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LecturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrivateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId")
                        .IsUnique()
                        .HasFilter("[LecturerId] IS NOT NULL");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.ToTable("User", "core");

                    b.HasData(
                        new
                        {
                            Id = new Guid("692e35ad-4672-4632-bde0-607abb8fa0b8"),
                            BirtsDate = new DateTime(2023, 7, 22, 13, 42, 49, 315, DateTimeKind.Local).AddTicks(4224),
                            CreatedDate = new DateTime(2023, 7, 22, 13, 42, 49, 315, DateTimeKind.Local).AddTicks(4210),
                            Email = "1",
                            FirstName = "admin",
                            IsDeleted = false,
                            LastName = "admin",
                            PasswordHash = new byte[] { 29, 75, 139, 229, 45, 15, 199, 111, 93, 170, 17, 198, 163, 161, 161, 143, 196, 82, 240, 3, 212, 137, 120, 167, 182, 231, 60, 224, 89, 244, 176, 232, 71, 32, 177, 138, 57, 51, 128, 37, 11, 106, 1, 69, 6, 174, 253, 62, 22, 35, 1, 148, 10, 155, 70, 48, 26, 15, 92, 53, 113, 224, 99, 126 },
                            PasswordSalt = new byte[] { 43, 130, 227, 178, 247, 137, 23, 234, 229, 161, 31, 15, 47, 128, 38, 171, 153, 195, 151, 221, 17, 81, 72, 91, 15, 244, 188, 50, 215, 61, 15, 99, 137, 145, 102, 72, 142, 21, 208, 159, 79, 221, 245, 171, 30, 127, 2, 231, 30, 22, 120, 35, 220, 149, 241, 202, 224, 18, 160, 67, 2, 216, 99, 36, 109, 72, 169, 156, 137, 34, 94, 242, 212, 242, 167, 224, 218, 77, 102, 200, 87, 140, 3, 151, 31, 112, 65, 244, 126, 11, 61, 1, 85, 201, 252, 118, 0, 101, 181, 22, 24, 123, 253, 36, 224, 210, 3, 20, 3, 177, 133, 131, 11, 71, 159, 228, 244, 40, 27, 248, 7, 127, 48, 244, 175, 176, 102, 39 },
                            PhoneNumber = "admin",
                            PrivateNumber = "admin",
                            Role = 0
                        });
                });

            modelBuilder.Entity("University.Domain.Entities.Exams.Exam", b =>
                {
                    b.HasOne("University.Domain.Entities.Lecturers.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.Subjects.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("University.Domain.Entities.LecturerSubjects.LecturerSubject", b =>
                {
                    b.HasOne("University.Domain.Entities.Lecturers.Lecturer", "Lecturer")
                        .WithMany("Subjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.Subjects.Subject", "Subject")
                        .WithMany("Lecturers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("University.Domain.Entities.StudentSubjectExams.StudentSubjectExam", b =>
                {
                    b.HasOne("University.Domain.Entities.Exams.Exam", "Exam")
                        .WithOne()
                        .HasForeignKey("University.Domain.Entities.StudentSubjectExams.StudentSubjectExam", "ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.StudentSubjects.StudentSubject", "StudentSubject")
                        .WithMany("StudentSubjectExams")
                        .HasForeignKey("StudentSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("StudentSubject");
                });

            modelBuilder.Entity("University.Domain.Entities.StudentSubjects.StudentSubject", b =>
                {
                    b.HasOne("University.Domain.Entities.Students.Student", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.Subjects.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("University.Domain.Entities.Students.Student", b =>
                {
                    b.HasOne("University.Domain.Entities.Faculties.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("University.Domain.Entities.Faculties.Faculty", null)
                        .WithMany("Students")
                        .HasForeignKey("FacultyId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("University.Domain.Entities.SubjectPrograms.SubjectProgram", b =>
                {
                    b.HasOne("University.Domain.Entities.Subjects.Subject", "Subject")
                        .WithMany("SubjectPrograms")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("University.Domain.Entities.Subjects.Subject", b =>
                {
                    b.HasOne("University.Domain.Entities.Faculties.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("University.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("University.Domain.Entities.Lecturers.Lecturer", "Lecturer")
                        .WithOne("User")
                        .HasForeignKey("University.Domain.Entities.Users.User", "LecturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("University.Domain.Entities.Students.Student", "Student")
                        .WithOne("User")
                        .HasForeignKey("University.Domain.Entities.Users.User", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lecturer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University.Domain.Entities.Faculties.Faculty", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("University.Domain.Entities.Lecturers.Lecturer", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("University.Domain.Entities.StudentSubjects.StudentSubject", b =>
                {
                    b.Navigation("StudentSubjectExams");
                });

            modelBuilder.Entity("University.Domain.Entities.Students.Student", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("University.Domain.Entities.Subjects.Subject", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Lecturers");

                    b.Navigation("Students");

                    b.Navigation("SubjectPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
